"""ISED amateur radio exam section titles and descriptions."""

from __future__ import annotations

SECTION_DESCRIPTIONS: dict[str, str] = {
    "A-001-001": "RC and RL time constants",
    "A-001-002": "Skin effect, capacitance, electromagnetic fields",
    "A-001-003": "Series RLC circuits: calculations",
    "A-001-004": "Parallel RLC circuits: calculations",
    "A-001-005": "RLC circuit Q: calculations",
    "A-002-001": "Semiconductor materials, P-type vs N-type, doping",
    "A-002-002": "Diodes: Zener, varactor, junction vs point-contact",
    "A-002-003": "Bipolar transistors: alpha, beta, common-base and common-emitter",
    "A-002-004": "FETs, JFETs, MOSFETs",
    "A-002-005": "Silicon-controlled rectifiers",
    "A-002-006": "Amplifiers: classes A, B, AB, C; efficiency, phase, linearity",
    "A-002-007": "FET input and output impedance; bipolar circuit inputs vs outputs",
    "A-002-008": "Operational amplifiers",
    "A-002-009": "Mixers and multipliers",
    "A-002-010": "Logic circuits: NAND, AND, OR, NOR, XOR, XNOR, flip-flops",
    "A-002-011": "Crystal lattice filters, crystal oscillators",
    "A-002-012": "LC filters: Butterworth, Chebyshev, cavities, helical resonators",
    "A-003-001": "Peak-to-peak vs RMS; sine waves, AC vs DC measurements",
    "A-003-002": "PEP vs RMS for RF power; Ohm's law for power, PEP calculation",
    "A-003-003": "Dip meters, signal generators, FM SINAD measurement",
    "A-003-004": "Frequency counters, timebase, marker generator, crystal calibrator",
    "A-003-005": "Oscilloscopes: use, accuracy",
    "A-003-006": "Voltmeters, ammeters, shunts",
    "A-004-001": "Transformer and rectifier circuits, voltage doubler, PIPs",
    "A-004-002": "Filter circuits, bleeder resistor functions",
    "A-004-003": "Linear and switching voltage regulator circuits",
    "A-004-004": "Regulated power supplies",
    "A-005-001": "Oscillators: Hartley, Colpitts, Pierce, VFOs, PLLs",
    "A-005-002": "Amplifier design: PI networks, PI-L networks, grounded-grid triode",
    "A-005-003": "Amplifier parasitics, neutralization",
    "A-005-004": "SSB: balanced modulator, carrier suppression, PEP, two-tone testing",
    "A-005-005": "FM: modulation index, deviation, central frequency",
    "A-005-006": "Intermod, phase modulation, repeaters, cavity filters",
    "A-005-007": "SSB transmitters, DSP",
    "A-005-008": "Digital modes: ASCII, Baudot, ARQ, AX.25, FEC, APRS",
    "A-005-009": "Spread spectrum",
    "A-006-001": "Superhet receivers: single- and double-conversion",
    "A-006-002": "Superhet receivers: IF, BFO, mixer",
    "A-006-003": "Receivers: noise floor, stage purposes, SINAD (FM)",
    "A-006-004": "Receivers: product detector, AGC, BFO",
    "A-006-005": "Receivers: selectivity, desense, intermod",
    "A-007-001": "Antenna tuners: transformers, series, L-network, PI network",
    "A-007-002": "Transmission lines: quarter-wave and half-wave transformers, velocity factor",
    "A-007-003": "Feeding antennas: T-match, gamma, omega, delta, stub",
    "A-007-004": "Antennas: current and voltage distribution, impedance",
    "A-007-005": "Antennas: polarization, Doppler, helical and parabolic antennas",
    "A-007-006": "Antennas: feedline loss, ERP, SWR, dB",
    "A-007-007": "Antennas: height effects on directivity, wave angle, dipole impedance",
    "A-007-008": "Antennas: radiation resistance, interaction, beamwidth, efficiency",
    "A-007-009": "Antennas: waveguide, microstrip line",
    "B-001-001": "Radio licences, applicability, eligibility of licence holder",
    "B-001-002": "Licence fee, term, posting requirements, change of address",
    "B-001-003": "Licence suspension or revocation, powers of radio inspectors, offences and punishments",
    "B-001-004": "Operator certificates, applicability, eligibility, equivalents, reciprocal recognition",
    "B-001-005": "Operation, repair and maintenance of radio apparatus on behalf of other persons",
    "B-001-006": "Operation of radio apparatus, terms of licence, applicable standards, exempt apparatus",
    "B-001-007": "Content restrictions – non-superfluous, profanity, secret code, music, non-commercial",
    "B-001-008": "Installation and operating restrictions – number of stations, repeaters, home-built, club stations",
    "B-001-009": "Participation in communications by visitors, use of station by others",
    "B-001-010": "Interference, determination, protection from interference",
    "B-001-011": "Emergency communications (real or simulated), communication with non-amateur stations",
    "B-001-012": "Non-remuneration, privacy of communications",
    "B-001-013": "Station identification, call signs, prefixes",
    "B-001-014": "Foreign amateur operation in Canada, banned countries, third-party messages",
    "B-001-015": "Frequency bands and qualification requirements",
    "B-001-016": "Maximum bandwidth by frequency bands",
    "B-001-017": "Restrictions on capacity and power output by qualifications",
    "B-001-018": "Unmodulated carriers, retransmission",
    "B-001-019": "Amplitude modulation, frequency stability, measurements",
    "B-001-020": "International Telecommunication Union (ITU) Radio Regulations, applicability",
    "B-001-021": "Operation outside Canada, ITU regions, reciprocal privileges, international licences",
    "B-001-022": "Examinations – delegated examinations, disabled accommodation",
    "B-001-023": "Antenna structure approval, neighbour and land-use authority consultation",
    "B-001-024": "Radio frequency electromagnetic field limits",
    "B-001-025": "Criteria for resolution of radio frequency interference complaints",
    "B-002-001": "Voice operating procedures – channelized VHF/UHF repeater",
    "B-002-002": "Phonetic alphabet",
    "B-002-003": "Voice operating procedures – simplex VHF/UHF and HF",
    "B-002-004": "Tuneups and testing, use of dummy load, courteous operation",
    "B-002-005": "Morse (CW) operating procedures, procedural signs",
    "B-002-006": "RST system of signal reporting, use of S meter",
    "B-002-007": "Q signals",
    "B-002-008": "Emergency operating procedures",
    "B-002-009": "Record keeping, confirmation practices, maps/charts, antenna orientation",
    "B-003-001": "Functional layout of HF stations",
    "B-003-002": "Functional layout of FM transmitters",
    "B-003-003": "Functional layout of FM receivers",
    "B-003-004": "Functional layout of CW transmitters",
    "B-003-005": "Functional layout of SSB/CW receivers",
    "B-003-006": "Functional layout of SSB transmitters",
    "B-003-007": "Functional layout of digital systems",
    "B-003-008": "Functional layout of regulated power supplies",
    "B-003-009": "Functional layout of Yagi-Uda antennas",
    "B-003-010": "Receiver fundamentals",
    "B-003-011": "Transmitter carrier, keying and amplitude modulation fundamentals",
    "B-003-012": "Carrier suppression, SSB fundamentals",
    "B-003-013": "Frequency and phase modulation fundamentals",
    "B-003-014": "Station accessories for telegraphy, radiotelephony and digital modes",
    "B-003-015": "Digital mode fundamentals: RTTY, ASCII, AMTOR, packet",
    "B-003-016": "Cells and batteries: types, ratings, charging",
    "B-003-017": "Power supply fundamentals",
    "B-003-018": "Electrical hazards, electrical safety, security",
    "B-003-019": "Electrical safety ground, capacitor discharge, fuse replacement",
    "B-003-020": "Antenna and tower safety, lightning protection",
    "B-003-021": "Exposure of human body to RF, safety precautions",
    "B-004-001": "Amplifier fundamentals",
    "B-004-002": "Diode fundamentals",
    "B-004-003": "Bipolar transistor fundamentals",
    "B-004-004": "Field-effect transistor fundamentals",
    "B-004-005": "Triode vacuum tube fundamentals",
    "B-004-006": "Resistor colour codes, tolerances, temperature coefficient",
    "B-005-001": "Metric prefixes: pico, micro, milli, centi, kilo, mega, giga",
    "B-005-002": "Concepts of current, voltage, conductor, insulator, resistance",
    "B-005-003": "Concepts of energy and power, open and short circuits",
    "B-005-004": "Ohm's law – single resistors",
    "B-005-005": "Series and parallel resistors",
    "B-005-006": "Power law, resistor power dissipation",
    "B-005-007": "AC, sine wave, frequency, frequency units",
    "B-005-008": "Ratios, logarithms, decibels",
    "B-005-009": "Introduction to inductance, capacitance",
    "B-005-010": "Introduction to reactance, impedance",
    "B-005-011": "Introduction to magnetics, transformers",
    "B-005-012": "Introduction to resonance, tuned circuits",
    "B-005-013": "Introduction to meters and measurements",
    "B-006-001": "Feedline characteristics, characteristic impedance",
    "B-006-002": "Balanced and unbalanced feedlines, baluns",
    "B-006-003": "Popular antenna feedline and coaxial connector types",
    "B-006-004": "Line losses by line type, length and frequency",
    "B-006-005": "Standing waves, standing wave ratio (SWR) meter",
    "B-006-006": "Concept of impedance matching",
    "B-006-007": "Isotropic source, polarization via element orientation",
    "B-006-008": "Wavelength vs physical length",
    "B-006-009": "Gain, directivity, radiation pattern, antenna bandwidth",
    "B-006-010": "Vertical antennas: types, dimensions, characteristics",
    "B-006-011": "Yagi antennas: types, dimensions, characteristics",
    "B-006-012": "Wire antennas: types, dimensions, characteristics",
    "B-006-013": "Quad/loop antennas: types, dimensions, characteristics",
    "B-007-001": "Line of sight, groundwave, ionospheric wave (sky wave)",
    "B-007-002": "Ionosphere, ionospheric regions (layers)",
    "B-007-003": "Propagation hops, skip zone, skip distance",
    "B-007-004": "Ionospheric absorption, fading, phase shift, Faraday rotation",
    "B-007-005": "Solar activity, sunspots, sunspot cycle",
    "B-007-006": "MF and HF: critical and maximum useable frequencies, solar flux",
    "B-007-007": "VHF and UHF: sporadic-E, aurora, ducting",
    "B-007-008": "Scatter: HF, VHF, UHF",
    "B-008-001": "Front-end overload, cross-modulation",
    "B-008-002": "Audio rectification, bypass capacitors, ferrites",
    "B-008-003": "Intermodulation, spurious emissions, key-clicks",
    "B-008-004": "Harmonics, splatter, transmitter adjustments",
    "B-008-005": "Use of filters: low-pass, high-pass, band-pass, band-reject",
}

def section_description(section: str) -> str:
    return SECTION_DESCRIPTIONS.get(section, section)
